version: "3.2"
services:
  iis:
    image: dtr.docker.ee/dev/iis:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        com.docker.lb.hosts: winlogo.apps.docker.ee
        com.docker.lb.network: frontend
        com.docker.lb.port: 80
    networks: 
      - frontend
networks:
  frontend:
    driver: overlay